import 'string_ids.dart';

const Map<String, String> english = {
  StringIds.appTitle: 'Personal Finance',
  StringIds.transactions: 'Transactions',
  StringIds.categories: 'Categories',
  StringIds.charts: 'Charts',
  StringIds.addExpense: 'Add Expense',
  StringIds.addIncome: 'Add Income',
  StringIds.addTransaction: 'Add Transaction',
  StringIds.editTransaction: 'Edit Transaction',
  StringIds.viewTransaction: 'Transaction Details',
  StringIds.balance: 'Balance',
  StringIds.amount: 'Amount',
  StringIds.category: 'Category',
  StringIds.date: 'Date',
  StringIds.notes: 'Notes',
  StringIds.type: 'Type',
  StringIds.income: 'Income',
  StringIds.expense: 'Expense',
  StringIds.save: 'Save',
  StringIds.delete: 'Delete',
  StringIds.edit: 'Edit',
  StringIds.cancel: 'Cancel',
  StringIds.errorLoading: 'Oops, something went wrong...',
  StringIds.retry: 'Retry',
  StringIds.errorSaving: 'Failed to save transaction',
  StringIds.errorDeleting: 'Failed to delete transaction',
  StringIds.errorLoadingTransaction: 'Failed to load transaction',
  StringIds.categoriesComingSoon: 'Categories will arrive soon.',
  StringIds.chartsComingSoon: 'Charts will arrive soon.',
  StringIds.noTransactions: 'No transactions yet',
  StringIds.notesOptional: 'Notes (optional)',
  StringIds.selectCategory: 'Select category',
  StringIds.selectDate: 'Select date',
  StringIds.filter: 'Filter',
  StringIds.all: 'All',
  StringIds.dateRange: 'Date Range',
  StringIds.applyFilters: 'Apply Filters',
  StringIds.clearFilters: 'Clear Filters',
  StringIds.spendingByCategory: 'Spending by Category',
  StringIds.deleteConfirmation: 'Are you sure you want to delete this transaction?',
};